CREATE TABLE [SCS_Auto_SRA].[scs_claim_payees](
	[iclaim_payee_id] [int] NOT NULL,
	[iclaim_id] [int] NOT NULL,
	[btpayee_default] [bit] NULL,
	[spayee_desc] [varchar](152) NULL,
	[spayee_type] [char](1) NOT NULL,
	[ipayee_id] [int] NULL,
	[spayee_no] [varchar](20) NULL,
	[spayee_name] [varchar](152) NULL,
	[spayee_addr_1] [varchar](30) NULL,
	[spayee_addr_2] [varchar](30) NULL,
	[spayee_city] [varchar](30) NULL,
	[spayee_state] [char](2) NULL,
	[spayee_zip_code] [varchar](10) NULL,
	[spayee_phone] [char](10) NULL,
	[spayee_fax] [char](10) NULL,
	[spay_method_code] [char](4) NULL,
	[clabor_rate] [money] NULL,
	[nlabor_tax_rate_1] [numeric](6, 5) NULL,
	[nlabor_tax_rate_2] [numeric](6, 5) NULL,
	[npart_markup] [numeric](6, 5) NULL,
	[npart_tax_rate_1] [numeric](6, 5) NULL,
	[npart_tax_rate_2] [numeric](6, 5) NULL,
	[supdate_user_id] [varchar](30) NULL,
	[iupdate_userid_type] [int] NULL,
	[dtupdate_last] [datetime] NULL,
	[spayee_language] [char](2) NULL,
	[stax_label_1] [varchar](60) NULL,
	[stax_label_2] [varchar](60) NULL,
	[btservicer_default] [bit] NULL,
	[sservice_notes] [varchar](255) NULL,
	[spayee_email] [varchar](100) NULL,
	[btcumulative] [bit] NOT NULL,
	[ccdelivery_method] [varchar](7) NULL,
	[uclaim_payee_uuid] [uniqueidentifier] ROWGUIDCOL  NOT NULL
) ON [PRIMARY]
GO

